### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "sathya@gmail.com",
  "password": "123456"
}

###

POST http://localhost:8080/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYXRoeWFAZ21haWwuY29tIiwiaWF0IjoxNzg1ODI3MDk5LCJleHAiOjE3ODU5MTM0OTl9.oQbwyHlTErtHsYj4Q4vscCD-nEC9aOelQpzxWfYGafs
Content-Type: application/json

{
  "accountType": "SAVINGS",
  "initialBalance": 5000
}

###

GET http://localhost:8080/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYXRoeWFAZ21haWwuY29tIiwiaWF0IjoxNzg1ODI3MDk5LCJleHAiOjE3ODU5MTM0OTl9.oQbwyHlTErtHsYj4Q4vscCD-nEC9aOelQpzxWfYGafs
